# Generated by Django 4.1.3 on 2022-11-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='password',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
